# Vectors and Linear Algebra

A *vector* is an ordered array of numbers (`list`) where each number has an assigned place.

Vectors are used to represent points in vector space.

Vectors must only contain numerical, usually floats.

Vectors in the same space must have the same number of dimensions.

In [1]:
import numpy as np

In [2]:
np.array(range(4))

array([0, 1, 2, 3])

In [4]:
x = np.array(range(4))
x

array([0, 1, 2, 3])

In [5]:
x[3] = 4

In [6]:
x

array([0, 1, 2, 4])

In [7]:
x * 2

array([0, 2, 4, 8])

## Vector length and normalization

length is also called *norm*

square each and take the root of the sum

In [8]:
x = np.array([3, 4])

In [9]:
np.linalg.norm(x)

np.float64(5.0)

In [10]:
y = x*2

In [11]:
y

array([6, 8])

In [12]:
np.linalg.norm(y)

np.float64(10.0)

In [13]:
x_normalized = x / np.linalg.norm(x)

In [14]:
x_normalized

array([0.6, 0.8])

In [15]:
np.linalg.norm(x_normalized)

np.float64(1.0)

Normalization scales the vector so all its dimensions are less than 1. Makes it easier to compute cosine distance between to vectors.

NameError: name 'dim' is not defined